### ISSUE TITLE
Plugin is nerabotaet

### ISSUE THREAD

**Issue by Mr1rbis** [U61vashka/PlasmoVoiceAddon#2]
issued server command: /musicurl https://www.youtube.com/watch?v=rciEQYlvzQw&t
[20:35:50 WARN]: [PlasmoVoiceAddon] Plugin PlasmoVoiceAddon v1.1.0 generated an exception while executing task 68
java.lang.IllegalArgumentException: Progress must be between 0.0 and 1.0 (-26.0)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.boss.CraftBossBar.setProgress(CraftBossBar.java:158) ~[purpur-1.19.jar:git-Purpur-1729]
        at com.ubivashka.plasmovoice.progress.InputStreamProgressWrapper.notifyListeners(InputStreamProgressWrapper.java:76) ~[PlasmoVoiceAddon.jar:?]
        at com.ubivashka.plasmovoice.progress.InputStreamProgressWrapper.evaluatePercent(InputStreamProgressWrapper.java:71) ~[PlasmoVoiceAddon.jar:?]
        at com.ubivashka.plasmovoice.progress.InputStreamProgressWrapper.read(InputStreamProgressWrapper.java:32) ~[PlasmoVoiceAddon.jar:?]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:244) ~[?:?]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:263) ~[?:?]
        at com.sun.media.sound.RIFFReader.read(RIFFReader.java:126) ~[?:?]
        at com.sun.media.sound.RIFFReader.<init>(RIFFReader.java:61) ~[?:?]
        at com.sun.media.sound.WaveExtensibleFileReader.getAudioFileFormatImpl(WaveExtensibleFileReader.java:172) ~[?:?]
        at com.sun.media.sound.SunFileReader.getAudioFileFormat(SunFileReader.java:54) ~[?:?]
        at com.sun.media.sound.SunFileReader.getAudioFileFormat(SunFileReader.java:47) ~[?:?]
        at javax.sound.sampled.AudioSystem.getAudioFileFormat(AudioSystem.java:924) ~[?:?]
        at com.ubivashka.plasmovoice.sound.SoundFormat$1.isValid(SoundFormat.java:16) ~[PlasmoVoiceAddon.jar:?]
        at com.ubivashka.plasmovoice.sound.SoundFormat.lambda$findMatchingSoundFormat$0(SoundFormat.java:42) ~[PlasmoVoiceAddon.jar:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
        at com.ubivashka.plasmovoice.sound.SoundFormat.findMatchingSoundFormat(SoundFormat.java:42) ~[PlasmoVoiceAddon.jar:?]
        at com.ubivashka.plasmovoice.sound.SoundBuilder.<init>(SoundBuilder.java:24) ~[PlasmoVoiceAddon.jar:?]
        at com.ubivashka.plasmovoice.commands.MusicCommand.playInputStream(MusicCommand.java:114) ~[PlasmoVoiceAddon.jar:?]
        at com.ubivashka.plasmovoice.commands.MusicCommand.lambda$executeUrlSubcommand$1(MusicCommand.java:66) ~[PlasmoVoiceAddon.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1729]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.jar:git-Purpur-1729]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:36:06 INFO]: UUID of player L0v1x is 30971c98-d483-3a8b-b23d-0b98d6a8c77b
[20:36:06 INFO]: L0v1x joined the game
[20:36:06 INFO]: L0v1x[/212.164.44.72:62518] logged in with entity id 461 at ([world]-12.726548565085858, 21.0, 6.241143274186113)
[20:36:41 INFO]: Daklad_ issued server command: /sit
> op MrIrbis
[20:37:24 INFO]: Made MrIrbis a server operator
[20:37:33 INFO]: MrIrbis issued server command: /bossbar remove
[20:37:36 INFO]: MrIrbis issued server command: /bossbar remove
[20:37:38 INFO]: MrIrbis issued server command: /bossbar remove
[20:37:39 INFO]: MrIrbis issued server command: /bossbar remove
[20:39:05 INFO]: MrIrbis issued server command: /musicfile Limizin.mp2
[20:39:09 INFO]: MrIrbis issued server command: /musicfile Limizin.mp3
[20:39:33 INFO]: MrIrbis issued server command: /musicfile Limuizin.mp3
[20:39:45 INFO]: MrIrbis issued server command: /musicfile Limuzin.mp3
[20:39:45 WARN]: java.io.IOException: Resetting to invalid mark
[20:39:45 WARN]:        at java.base/java.io.BufferedInputStream.reset(BufferedInputStream.java:446)
[20:39:45 WARN]:        at PlasmoVoiceAddon.jar//com.ubivashka.plasmovoice.sound.SoundBuilder.build(SoundBuilder.java:34)
[20:39:45 WARN]:        at PlasmoVoiceAddon.jar//com.ubivashka.plasmovoice.commands.MusicCommand.playInputStream(MusicCommand.java:114)
[20:39:45 WARN]:        at PlasmoVoiceAddon.jar//com.ubivashka.plasmovoice.commands.MusicCommand.lambda$executeFileSubcommand$0(MusicCommand.java:39)
[20:39:45 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:39:45 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:39:45 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:39:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:39:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:39:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[20:39:52 INFO]: MrIrbis issued server command: /musicfile reload
[20:40:04 INFO]: MrIrbis issued server command: /music force file
[20:40:13 INFO]: MrIrbis issued server command: /music reload
[20:40:32 INFO]: MrIrbis issued server command: /musicfile Limuzin.mp3
[20:40:32 WARN]: java.io.IOException: Resetting to invalid mark
[20:40:32 WARN]:        at java.base/java.io.BufferedInputStream.reset(BufferedInputStream.java:446)
[20:40:32 WARN]:        at PlasmoVoiceAddon.jar//com.ubivashka.plasmovoice.sound.SoundBuilder.build(SoundBuilder.java:34)
[20:40:32 WARN]:        at PlasmoVoiceAddon.jar//com.ubivashka.plasmovoice.commands.MusicCommand.playInputStream(MusicCommand.java:114)
[20:40:32 WARN]:        at PlasmoVoiceAddon.jar//com.ubivashka.plasmovoice.commands.MusicCommand.lambda$executeFileSubcommand$0(MusicCommand.java:39)
[20:40:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:40:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:40:32 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:40:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:40:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:40:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Mr1rbis** [comment]
Почему плагин это пишет?

**Comment by bivashy** [comment]
Плагин не поддерживает ютуб ссылки.

Их поддержка будет скоро

А так же было исправлено кое какие недоработки

**Comment by bivashy** [comment]
Исправлено в последнем обновлении (>1.2.0-pre.1)
 
Fixed in last update (>1.2.0-pre.1)
